PROVIDER = "virtualbox"
IMAGE_NAME = "archlinux/archlinux"
NO_WORKERS = 2

Vagrant.configure("2") do |config|
    # https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html#config-ssh-insert_key
    config.ssh.insert_key = false

    config.vm.provider PROVIDER do |v|
        v.memory = 1024
        v.cpus = 2
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end

    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        # configure master using static ip in private network
        # https://www.vagrantup.com/docs/networking/private_network.html#static-ip
        master.vm.network "private_network", ip: "192.168.50.10"
        # alternatively we could use dhcp
        #config.vm.network "private_network", type: "dhcp"
        master.vm.hostname = "k8s-master"
    end

    (1..NO_WORKERS).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            # configure worker node using static ip in private network
            node.vm.network "private_network", ip: "192.168.50.#{i + 10}"
            # alternatively we could use dhcp
            #config.vm.network "private_network", type: "dhcp"
            node.vm.hostname = "node-#{i}"
        end
    end

    # we need to install python to interact on the nodes using Ansible
    config.vm.provision "shell", inline: "pacman -S python --noconfirm"
end
